version: "3.8"

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    restart: always

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot_db
